import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import header from '../components/header'
import PostBox from '../components/PostBox'
import Feed from '../components/Feed'
const Home: NextPage = () => {
  return (
    <div className="my-7 mx-auto max-w-5xl p-8 pt-0">
      <Head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="Generated by create next app" />
        <title>Reddit Clone</title>


        
      </Head>

      {/*PostBox*/}
<PostBox />
      <div className="flex">
     
       <Feed />
      </div>

      
    </div>
  )
}

export default Home
